#!/bin/sh

set -e
set -x

# installation pathes are based of ORIENTDB_HOME
export ORIENTDB_HOME="$SNAP"
# writable pathes are based of ORIENTDB_BASE
export ORIENTDB_BASE="$SNAP_DATA"

# create runtime data
mkdir -p "$ORIENTDB_BASE/log"
mkdir -p "$ORIENTDB_BASE/databases"

$ORIENTDB_HOME/bin/server.sh -Dserver.database.path=$ORIENTDB_BASE/databases