name: orientdb
version: "2.2.13"
summary: OrientDB multi-nodel database
description: OrientDB multi-nodel database
confinement: strict

apps:
  orientdb:
    command: bin/server.sh

parts:
  orientdb-package:
    plugin: dump
    source-type: tar
    source: http://central.maven.org/maven2/com/orientechnologies/orientdb-community/2.2.13/orientdb-community-2.2.13.tar.gz
  oriendb:
    after:
      - orientdb-package
    stage-packages:
      - default-jdk
    snap:
      - usr/lib/jvm
