name: orientdb
version: "2.2.13"
summary: OrientDB multi-nodel database
description: OrientDB multi-nodel database
confinement: strict

apps:
  orientdb:
    command: bin/wrapper
    daemon: simple
    stop-command: bin/shutdown.sh
    stop-timeout: 5s
    plugs:
      - network

parts:
  orientdb:
    plugin: dump
    source-type: tar
    source: http://central.maven.org/maven2/com/orientechnologies/orientdb-community/2.2.13/orientdb-community-2.2.13.tar.gz
    stage-packages: 
      - default-jdk
    snap:
      - usr/lib/jvm/default-java/bin
      - usr/lib/jvm/default-java/lib
      - usr/lib/jvm/default-java/jre/bin
      - usr/lib/jvm/default-java/jre/lib
      - etc/java-*
      - bin
      - databases
      - config
  glue:
    plugin: dump
    source: .
    organize:
      orientdb: bin/wrapper
    snap:
        - bin/*
